"""Command surface for the Prosper or Perish constructor workspace."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import shutil
import signal
import subprocess
import sys
import time
import tomllib
from pathlib import Path
from typing import Any, Sequence


ROOT_MARKER = "constructor.toml"
CONSTRUCTOR_PROFILE = "constructor"
CONSTRUCTOR_LOAD_ORDER = Path("constructor.load_order.toml")
SAVEGAME_DATASET = Path("graphs/dataset")
SAVEGAME_NOTEBOOK_DATA = Path("graphs/savegame_notebooks/data")
SAVEGAME_LEGACY_DATASETS = (
    Path("graphs/dataset_v2"),
    Path("graphs/savegame_progression_dataset"),
    Path("artifacts/data/savegame_progression"),
    Path("graphs/dashboard_benchmark_report.json"),
)
SAVEGAME_ARTIFACT_DIR = Path("artifacts/data/savegame")
SYNC_STATE_PATH = Path("artifacts/sync/state.json")
SYNC_STAGES = ("labeling", "blueprints", "population_capacity")
GOODS_FLOW_EXPLORER = Path("graphs/goods_flow_explorer.html")
PUBLISHED_GOODS_FLOW_EXPLORER = Path("docs/examples/goods_flow_explorer.html")
SAVEGAME_EXPLORER = Path("graphs/savegame_explorer.html")
SAVEGAME_PROGRESSION_EXPLORER = Path("graphs/savegame_progression.html")
PUBLISHED_SAVEGAME_EXPLORER = Path("docs/examples/savegame_explorer.html")
PUBLISHED_GRAPH_EXAMPLES = (
    GOODS_FLOW_EXPLORER.name,
    SAVEGAME_EXPLORER.name,
)
SAVEGAME_PURGE_PATHS = (
    SAVEGAME_ARTIFACT_DIR,
    SAVEGAME_EXPLORER,
    SAVEGAME_PROGRESSION_EXPLORER,
    PUBLISHED_SAVEGAME_EXPLORER,
    SAVEGAME_DATASET,
    SAVEGAME_NOTEBOOK_DATA,
    *SAVEGAME_LEGACY_DATASETS,
)
LOCATION_POTENTIAL_CONCEPT_LINES = (
    "  # Start generated location potential concept",
    '  game_concept_pp_location_potential: "Location Potential"',
    '  game_concept_pp_location_potential_desc: "Location Potential is the shared calculation behind Prosper or Perish per-location population capacity and local output modifiers.\\n\\nThe values combine in-game geography with external map-derived evidence. They are meant to represent how suitable each location is for supporting people and producing local raw materials.\\n\\n#T In-game factors:#!\\n$BULLET$ Topography\\n$BULLET$ Climate\\n$BULLET$ Vegetation\\n$BULLET$ River access\\n$BULLET$ Lake access\\n$BULLET$ Coastal access\\n$BULLET$ Location RGO\\n\\n#T Out-of-game maps and evidence:#!\\n$BULLET$ Soil data\\n$BULLET$ GAEZ crop potential and suitability maps\\n$BULLET$ HYDE historical population coverage\\n$BULLET$ Freshwater food support maps\\n$BULLET$ Marine food support maps\\n$BULLET$ Livestock food support maps\\n$BULLET$ Plant food support maps\\n$BULLET$ Wild subsistence support maps\\n$BULLET$ Land-use confidence maps\\n$BULLET$ Water confidence maps\\n\\nThe modelling and pipeline for this are in the GitHub repo, but they are subject to change. The final numbers are generated by the constructor pipeline, then injected into the shared per-location static modifiers used by the mod."',
    "  # End generated location potential concept",
)
LOCATION_MODIFIER_ALIASES = {
    "pp_loc_washita": "pp_loc_washita_pp",
}
BOM_TEXT_RELATIVE_PATHS = (
    Path("main_menu/common/game_concepts/pp_location_potential.txt"),
    Path("main_menu/common/static_modifiers/pp_capacity_pressure_effects.txt"),
    Path("main_menu/common/static_modifiers/pp_location_modifier_adjustments.txt"),
    Path("main_menu/common/static_modifiers/pp_location_modifiers.txt"),
    Path("in_game/common/climates/pp_climate_changes.txt"),
    Path("in_game/common/vegetation/pp_vegetation_changes.txt"),
    Path("in_game/common/topography/pp_topography_changes.txt"),
    Path("in_game/common/static_modifiers/pp_rgo_static_bonuses.txt"),
    Path("in_game/common/estate_privileges/pp_estate_privilege_adjustments.txt"),
    Path("in_game/common/societal_values/pp_societal_value_adjustments.txt"),
    Path("in_game/common/location_ranks/pp_location_rank_adjustments.txt"),
    Path("in_game/common/advances/pp_local_resource_productivity_advances.txt"),
    Path("in_game/common/advances/pp_prosperity_advances_adjustments.txt"),
    Path("in_game/gfx/map/map_modes/pp_local_output_modifier_map_modes.txt"),
    Path("in_game/common/on_action/pp_apply_location_modifiers.txt"),
    Path("in_game/common/building_types/pp_aqueduct_system.txt"),
)
PRICE_MODIFIER_TYPE_DEFINITIONS = Path(
    "main_menu/common/modifier_type_definitions/pp_modifier_types.txt"
)
PRICE_MODIFIER_ICONS = Path("main_menu/common/modifier_icons/pp_price_modifier_icons.txt")
PRICE_MODIFIER_LOCALIZATION = Path("main_menu/localization/english/pp_modifier_types_l_english.yml")


def main(argv: Sequence[str] | None = None) -> int:
    parser = _build_parser()
    args, extra = parser.parse_known_args(argv)

    repo = _resolve_repo(args.repo)
    project = repo / args.project

    try:
        return args.handler(args, extra, repo, project)
    except KeyboardInterrupt:
        return 130


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ppc",
        description="Prosper or Perish constructor workflow commands.",
    )
    parser.add_argument(
        "--repo",
        type=Path,
        default=None,
        help="Repository root. Defaults to the nearest parent containing constructor.toml.",
    )
    parser.add_argument(
        "--project",
        default=ROOT_MARKER,
        help="Project TOML path relative to --repo. Defaults to constructor.toml.",
    )

    subcommands = parser.add_subparsers(dest="command", required=True)

    _add_command(
        subcommands,
        "setup",
        "Install dev dependencies, then inspect the constructor project.",
        _setup,
    )
    _add_command(
        subcommands,
        "inspect",
        "Inspect the configured constructor project.",
        _orchestrator("inspect"),
    )
    _add_command(
        subcommands,
        "test",
        "Run pytest. Extra args are passed to pytest.",
        _test,
    )
    _add_command(
        subcommands,
        "analyze",
        "Export static parser tables and refresh the goods-flow docs example.",
        _analyze,
    )
    output_modifiers = _add_command(
        subcommands,
        "output-modifiers",
        "Print cumulative global output modifiers by good and age.",
        _output_modifiers,
    )
    output_modifiers.add_argument(
        "--include-specific",
        action="store_true",
        help="Include output modifiers from advancements with potential-specific gates.",
    )
    output_modifiers.add_argument(
        "--load-order",
        type=Path,
        default=CONSTRUCTOR_LOAD_ORDER,
        help="Load-order TOML path relative to --repo. Defaults to constructor.load_order.toml.",
    )
    output_modifiers.add_argument(
        "--profile",
        default=CONSTRUCTOR_PROFILE,
        help="Parser profile from the load-order TOML. Defaults to constructor.",
    )
    production_throughput = _add_command(
        subcommands,
        "production-throughput",
        "Print best building production throughput by good and age.",
        _production_throughput,
    )
    production_throughput.add_argument(
        "--include-specific",
        action="store_true",
        help="Include production methods with potential-specific gates.",
    )
    production_throughput.add_argument(
        "--load-order",
        type=Path,
        default=CONSTRUCTOR_LOAD_ORDER,
        help="Load-order TOML path relative to --repo. Defaults to constructor.load_order.toml.",
    )
    production_throughput.add_argument(
        "--profile",
        default=CONSTRUCTOR_PROFILE,
        help="Parser profile from the load-order TOML. Defaults to constructor.",
    )
    _add_command(
        subcommands,
        "savegame",
        "Export latest savegame facts and the savegame explorer.",
        _savegame,
    )
    savegame_purge = _add_command(
        subcommands,
        "savegame-purge",
        "Delete generated savegame analysis artifacts and notebook datasets.",
        _savegame_purge,
    )
    savegame_purge.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated savegame paths that would be deleted without deleting them.",
    )
    _add_command(
        subcommands,
        "publish-docs",
        "Copy generated graph outputs into docs/examples.",
        _publish_docs,
    ).add_argument(
        "examples",
        nargs="*",
        help="Optional graph HTML files to publish. Defaults to all examples.",
    )
    dashboard = _add_command(
        subcommands,
        "dashboard",
        "Serve the local population-capacity dashboard.",
        _dashboard,
    )
    dashboard.add_argument(
        "--host",
        default="127.0.0.1",
        help="Host interface for the local dashboard server. Defaults to 127.0.0.1.",
    )
    dashboard.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Port for the local dashboard server. Defaults to 8000.",
    )
    dashboard.add_argument(
        "--dir",
        type=Path,
        default=Path("artifacts/data/population_capacity/current_capacity_map"),
        help="Dashboard directory relative to --repo. Defaults to the current capacity map dashboard.",
    )
    savegame_notebooks = subcommands.add_parser(
        "savegame-notebooks",
        help="Build RAM-efficient parquet data for savegame notebooks.",
        description="Savegame notebook commands using the constructor profile and load order.",
    )
    savegame_notebooks_subcommands = savegame_notebooks.add_subparsers(
        dest="savegame_notebooks_command",
        required=True,
    )
    savegame_notebooks_build = _add_savegame_notebooks_command(
        savegame_notebooks_subcommands,
        "build",
        "Ingest savegames, then write notebook-ready parquet data.",
        _savegame_notebooks_build,
    )
    savegame_notebooks_build.add_argument(
        "--save-dir",
        type=Path,
        default=None,
        help="Directory containing .eu5 saves. Defaults to auto-detecting the EU5 documents save folder.",
    )
    savegame_notebooks_build.add_argument(
        "--workers",
        type=int,
        default=4,
        help="Parallel save parser workers. Defaults to 4.",
    )
    savegame_notebooks_build.add_argument(
        "--no-ingest",
        action="store_true",
        help="Only rebuild notebook parquet from an existing graphs/dataset.",
    )
    savegame_notebooks_build.add_argument(
        "--force",
        action="store_true",
        help="Rebuild notebook parquet even when existing output metadata is current.",
    )
    _add_command(
        subcommands,
        "build",
        "Build accepted blueprints into the constructor mod copy with --overwrite.",
        _build,
    )

    sync = _add_command(
        subcommands,
        "sync",
        "RISKY: incrementally build and mirror the constructor mod into the live Paradox mod folder.",
        _sync,
    )
    sync.add_argument(
        "--yes",
        action="store_true",
        help="Required confirmation for live mod folder mirroring.",
    )
    sync.add_argument(
        "--force-build",
        action="store_true",
        help="Run smart sync generator stages even when their fingerprints are unchanged.",
    )
    sync.add_argument(
        "--force-deploy",
        action="store_true",
        help="Copy all built mod files to the live target even when they look unchanged.",
    )
    sync.add_argument(
        "--full-build",
        action="store_true",
        help="Use the previous full eu5-orchestrator build workflow before deploy.",
    )

    blueprint = subcommands.add_parser(
        "blueprint",
        help="Run blueprint list, parity, evaluate, good, or build workflows.",
        description="Blueprint workflow commands. Extra args are passed to eu5-orchestrator.",
    )
    blueprint_subcommands = blueprint.add_subparsers(dest="blueprint_command", required=True)
    _add_command(blueprint_subcommands, "list", "List accepted blueprints.", _blueprint("list"))
    _add_command(
        blueprint_subcommands,
        "parity",
        "Check blueprint output parity against generated mod files.",
        _blueprint("parity"),
    )
    _add_command(
        blueprint_subcommands,
        "evaluate",
        "Evaluate accepted blueprint economics and balance rules.",
        _blueprint("evaluate"),
    )
    good = _add_command(
        blueprint_subcommands,
        "good",
        "Compare production methods that produce one trade good.",
        _blueprint_good,
    )
    good.add_argument("good", help="Trade good id, for example coal or victuals.")
    _add_command(
        blueprint_subcommands,
        "build",
        "Build accepted blueprints into the constructor mod copy with --overwrite.",
        _build,
    )

    return parser


def _add_command(
    subcommands: argparse._SubParsersAction[argparse.ArgumentParser],
    name: str,
    help_text: str,
    handler,
) -> argparse.ArgumentParser:
    command = subcommands.add_parser(
        name,
        help=help_text,
        description=f"{help_text} Use '--' before extra tool arguments when needed.",
    )
    command.set_defaults(handler=handler)
    return command


def _add_savegame_notebooks_command(
    subcommands: argparse._SubParsersAction[argparse.ArgumentParser],
    name: str,
    help_text: str,
    handler,
) -> argparse.ArgumentParser:
    command = subcommands.add_parser(name, help=help_text, description=help_text)
    command.add_argument(
        "--dataset",
        type=Path,
        default=SAVEGAME_DATASET,
        help="Raw savegame parquet dataset directory relative to --repo. Defaults to graphs/dataset.",
    )
    command.add_argument(
        "--output",
        type=Path,
        default=SAVEGAME_NOTEBOOK_DATA,
        help=(
            "Deprecated. Notebooks now read the raw --dataset parquet directory directly; "
            "this option is ignored."
        ),
    )
    command.add_argument(
        "--load-order",
        type=Path,
        default=CONSTRUCTOR_LOAD_ORDER,
        help="Load-order TOML path relative to --repo. Defaults to constructor.load_order.toml.",
    )
    command.add_argument(
        "--profile",
        default=CONSTRUCTOR_PROFILE,
        help="Parser profile from the load-order TOML. Defaults to constructor.",
    )
    command.set_defaults(handler=handler)
    return command


def _resolve_repo(repo: Path | None) -> Path:
    if repo is not None:
        resolved = repo.expanduser().resolve()
        _require_project_root(resolved)
        return resolved

    current = Path.cwd().resolve()
    for candidate in (current, *current.parents):
        if (candidate / ROOT_MARKER).is_file():
            return candidate

    raise SystemExit(
        f"Could not find {ROOT_MARKER}. Run from the repo or pass --repo /path/to/repo."
    )


def _require_project_root(repo: Path) -> None:
    if not (repo / ROOT_MARKER).is_file():
        raise SystemExit(f"{repo} does not look like this constructor repo; missing {ROOT_MARKER}.")


def _run(command: Sequence[str | os.PathLike[str]], repo: Path) -> int:
    printable = " ".join(str(part) for part in command)
    print(f"$ {printable}", flush=True)
    completed = subprocess.run([str(part) for part in command], cwd=repo, check=False)
    return completed.returncode


def _run_collecting_output(
    command: Sequence[str | os.PathLike[str]],
    repo: Path,
) -> tuple[int, str]:
    printable = " ".join(str(part) for part in command)
    print(f"$ {printable}", flush=True)
    completed = subprocess.run(
        [str(part) for part in command],
        cwd=repo,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    if completed.stdout:
        print(completed.stdout, end="" if completed.stdout.endswith("\n") else "\n", flush=True)
    return completed.returncode, completed.stdout or ""


def _orchestrator(action: str):
    def handler(args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path) -> int:
        return _run(["eu5-orchestrator", action, "--project", project, *extra], repo)

    return handler


def _blueprint(action: str):
    def handler(args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path) -> int:
        result = _run(["eu5-orchestrator", "blueprint", action, "--project", project, *extra], repo)
        if result == 0 and action == "build":
            _finalize_constructor_mod(repo, project)
        return result

    return handler


def _blueprint_good(
    args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path
) -> int:
    return _run(
        ["eu5-orchestrator", "blueprint", "good", "--project", project, "--good", args.good, *extra],
        repo,
    )


def _setup(args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path) -> int:
    if extra:
        raise SystemExit("setup does not accept extra arguments.")

    sync_code = _run(["uv", "sync", "--dev"], repo)
    if sync_code != 0:
        return sync_code
    return _run(["eu5-orchestrator", "inspect", "--project", project], repo)


def _test(args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path) -> int:
    pytest_args = list(extra)
    if not any(arg == "-s" or arg == "--capture" or arg.startswith("--capture=") for arg in pytest_args):
        pytest_args.insert(0, "--capture=no")
    return _run([sys.executable, "-m", "pytest", *pytest_args], repo)


def _build(args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path) -> int:
    build_code = _run(["eu5-orchestrator", "build", "--project", project, "--overwrite", *extra], repo)
    if build_code != 0:
        return build_code
    _finalize_constructor_mod(repo, project)
    return 0


def _finalize_constructor_mod(repo: Path, project: Path) -> None:
    mod_root = _project_mod_root(repo, project)
    _ensure_location_modifier_application_on_action(mod_root)
    _apply_location_modifier_aliases(mod_root)
    _ensure_price_cost_modifier_assets(mod_root)
    _ensure_constructor_text_boms(mod_root)
    _inject_location_potential_localization(mod_root)


def _project_mod_root(repo: Path, project: Path) -> Path:
    with project.open("rb") as handle:
        config = tomllib.load(handle)
    try:
        configured = config["project"]["mod_root"]
    except KeyError as error:
        raise SystemExit(f"Missing [project].mod_root in {project}") from error
    if not isinstance(configured, str):
        raise SystemExit(f"[project].mod_root must be a string in {project}")
    mod_root = Path(configured)
    return mod_root if mod_root.is_absolute() else repo / mod_root


def _inject_location_potential_localization(mod_root: Path) -> None:
    localization_root = mod_root / "main_menu" / "localization" / "english"
    modifiers_path = mod_root / "main_menu" / "common" / "static_modifiers" / "pp_location_modifiers.txt"
    modifier_localization_path = localization_root / "pp_location_modifiers_l_english.yml"
    europedia_localization_path = localization_root / "pp_europedia_l_english.yml"
    if not modifiers_path.is_file():
        raise SystemExit(
            "Cannot inject Location Potential localization; "
            f"missing generated modifiers file: {modifiers_path}"
        )

    location_modifiers = _location_modifier_keys(modifiers_path)
    if not location_modifiers:
        raise SystemExit(f"Cannot inject Location Potential localization; no pp_loc_* modifiers found in {modifiers_path}")

    modifier_lines = [
        "  # Start generated location potential modifier help",
        '  pp_location_potential_modifier_name: "[pp_location_potential|e]"',
        '  pp_location_potential_modifier_desc: "Population capacity and local output modifiers for this location are calculated from [pp_location_potential|e]."',
    ]
    for modifier_key in location_modifiers:
        modifier_lines.append(f'  STATIC_MODIFIER_NAME_{modifier_key}: "$pp_location_potential_modifier_name$"')
        modifier_lines.append(f'  STATIC_MODIFIER_DESC_{modifier_key}: "$pp_location_potential_modifier_desc$"')
    modifier_lines.append("  # End generated location potential modifier help")

    _write_text_if_changed(
        modifier_localization_path,
        "l_english:\n" + "\n".join(modifier_lines) + "\n",
        encoding="utf-8-sig",
    )
    _upsert_generated_localization_block(
        europedia_localization_path,
        "  # Start generated location potential concept",
        "  # End generated location potential concept",
        ("game_concept_pp_location_potential", "game_concept_pp_location_potential_desc"),
        LOCATION_POTENTIAL_CONCEPT_LINES,
    )
    print(
        f"Injected shared Location Potential localization for {len(location_modifiers)} location modifiers.",
        flush=True,
    )


def _apply_location_modifier_aliases(mod_root: Path) -> None:
    targets = (
        mod_root / "main_menu" / "common" / "static_modifiers" / "pp_location_modifiers.txt",
        mod_root / "in_game" / "common" / "on_action" / "pp_apply_location_modifiers.txt",
    )
    for path in targets:
        if not path.is_file():
            continue
        text = _read_text_preserving_newlines(path, encoding="utf-8-sig")
        updated = text
        for source, alias in LOCATION_MODIFIER_ALIASES.items():
            updated = re.sub(
                rf"(?<![A-Za-z0-9_]){re.escape(source)}(?![A-Za-z0-9_])",
                alias,
                updated,
            )
        _write_text_if_changed(path, updated, encoding="utf-8-sig", newline="")


def _ensure_location_modifier_application_on_action(mod_root: Path) -> None:
    path = mod_root / "in_game" / "common" / "on_action" / "pp_apply_location_modifiers.txt"
    if not path.is_file():
        return

    text = _read_text_preserving_newlines(path, encoding="utf-8-sig")
    newline = "\r\n" if "\r\n" in text else "\n"
    registration_block = (
        f"on_game_start = {{{newline}"
        f"\ton_actions = {{{newline}"
        f"\t\tpp_apply_location_modifiers{newline}"
        f"\t}}{newline}"
        f"}}{newline}"
        f"{newline}"
    )
    has_named_action = re.search(r"(?m)^pp_apply_location_modifiers\s*=\s*\{", text)
    has_self_registration = re.search(r"(?m)^\s*pp_apply_location_modifiers\s*$", text)
    if has_named_action and has_self_registration:
        return

    if has_named_action:
        updated = text.replace(
            "pp_apply_location_modifiers = {",
            registration_block + "pp_apply_location_modifiers = {",
            1,
        )
    else:
        old_header = f"on_game_start = {{{newline}\teffect = {{"
        new_header = registration_block + f"pp_apply_location_modifiers = {{{newline}\teffect = {{"
        updated = text.replace(old_header, new_header, 1)
    if updated == text:
        raise SystemExit(f"Cannot finalize generated location modifier on_action in {path}")
    _write_text_if_changed(path, updated, encoding="utf-8-sig", newline="")


def _ensure_price_cost_modifier_assets(mod_root: Path) -> None:
    modifier_keys = [f"{price_key}_cost_modifier" for price_key in _pp_price_keys(mod_root)]
    if not modifier_keys:
        return

    _upsert_price_cost_modifier_types(mod_root, modifier_keys)
    _write_price_cost_modifier_icons(mod_root, modifier_keys)
    _append_missing_price_cost_modifier_localization(mod_root, modifier_keys)


def _pp_price_keys(mod_root: Path) -> list[str]:
    prices_root = mod_root / "in_game" / "common" / "prices"
    if not prices_root.is_dir():
        return []

    keys: set[str] = set()
    pattern = re.compile(r"(?m)^\s*(pp_[A-Za-z0-9_]+_price)\s*=\s*\{")
    for path in sorted(prices_root.glob("pp_*.txt")):
        text = path.read_text(encoding="utf-8-sig")
        keys.update(pattern.findall(text))
    return sorted(keys)


def _upsert_price_cost_modifier_types(mod_root: Path, modifier_keys: Sequence[str]) -> None:
    path = mod_root / PRICE_MODIFIER_TYPE_DEFINITIONS
    if path.is_file():
        text = path.read_text(encoding="utf-8-sig").rstrip()
    else:
        text = ""
        path.parent.mkdir(parents=True, exist_ok=True)

    existing = _top_level_keys(text)
    missing = [key for key in modifier_keys if key not in existing]
    if not missing:
        return

    blocks = [_price_cost_modifier_type_block(key) for key in missing]
    updated = "\n\n".join(part for part in (text, "\n\n".join(blocks)) if part).rstrip() + "\n"
    _write_text_if_changed(path, updated, encoding="utf-8-sig")


def _price_cost_modifier_type_block(modifier_key: str) -> str:
    return "\n".join(
        (
            f"{modifier_key}={{",
            "\tcolor=bad",
            "\tpercent=yes",
            "\tgame_data={",
            "\t\tcategory=country",
            "\t}",
            "}",
        )
    )


def _write_price_cost_modifier_icons(mod_root: Path, modifier_keys: Sequence[str]) -> None:
    path = mod_root / PRICE_MODIFIER_ICONS
    path.parent.mkdir(parents=True, exist_ok=True)
    keys_defined_elsewhere = _modifier_icon_keys(mod_root, exclude=path)
    keys = [key for key in modifier_keys if key not in keys_defined_elsewhere]
    if not keys and not path.exists():
        return

    lines = [
        "# Prosper or Perish - generated building price cost modifier icons.",
        "# Generated from in_game/common/prices/pp_*.txt by the ppc finalizer.",
        "",
    ]
    for key in keys:
        lines.extend(
            (
                f"{key} = {{",
                '\tpositive = "gfx/interface/icons/modifier_types/_default.dds"',
                "}",
            )
        )
    _write_text_if_changed(path, "\n".join(lines).rstrip() + "\n", encoding="utf-8-sig")


def _modifier_icon_keys(mod_root: Path, *, exclude: Path) -> set[str]:
    icons_root = mod_root / "main_menu" / "common" / "modifier_icons"
    if not icons_root.is_dir():
        return set()

    keys: set[str] = set()
    for path in sorted(icons_root.glob("*.txt")):
        if path == exclude:
            continue
        keys.update(_top_level_keys(path.read_text(encoding="utf-8-sig")))
    return keys


def _append_missing_price_cost_modifier_localization(
    mod_root: Path,
    modifier_keys: Sequence[str],
) -> None:
    localization_root = mod_root / "main_menu" / "localization" / "english"
    localization_root.mkdir(parents=True, exist_ok=True)
    existing_name_keys: set[str] = set()
    existing_desc_keys: set[str] = set()
    for path in sorted(localization_root.glob("*.yml")):
        text = path.read_text(encoding="utf-8-sig", errors="replace")
        existing_name_keys.update(re.findall(r"(?m)^\s*MODIFIER_TYPE_NAME_([A-Za-z0-9_]+):", text))
        existing_desc_keys.update(re.findall(r"(?m)^\s*MODIFIER_TYPE_DESC_([A-Za-z0-9_]+):", text))

    target = mod_root / PRICE_MODIFIER_LOCALIZATION
    if target.is_file():
        text = target.read_text(encoding="utf-8-sig").rstrip()
    else:
        text = "l_english:"

    lines: list[str] = []
    for modifier_key in modifier_keys:
        building_key = modifier_key.removeprefix("pp_").removesuffix("_price_cost_modifier")
        display_name = _title_from_key(building_key)
        if modifier_key not in existing_desc_keys:
            lines.append(
                f'  MODIFIER_TYPE_DESC_{modifier_key}: "Affects the cost of building [ShowBuildingTypeName(\'{building_key}\')|e]."'
            )
        if modifier_key not in existing_name_keys:
            lines.append(f'  MODIFIER_TYPE_NAME_{modifier_key}: "{display_name} Cost"')

    if not lines:
        return
    updated = text + "\n" + "\n".join(lines) + "\n"
    _write_text_if_changed(target, updated, encoding="utf-8-sig")


def _title_from_key(key: str) -> str:
    return " ".join(part.capitalize() for part in key.split("_"))


def _top_level_keys(text: str) -> set[str]:
    return set(re.findall(r"(?m)^\ufeff?([A-Za-z0-9_]+)\s*=\s*\{", text))


def _ensure_constructor_text_boms(mod_root: Path) -> None:
    for relative_path in BOM_TEXT_RELATIVE_PATHS:
        path = mod_root / relative_path
        if not path.is_file():
            continue
        _write_text_if_changed(
            path,
            _read_text_preserving_newlines(path, encoding="utf-8-sig"),
            encoding="utf-8-sig",
            newline="",
        )


def _location_modifier_keys(modifiers_path: Path) -> list[str]:
    seen: set[str] = set()
    modifiers: list[str] = []
    for line in modifiers_path.read_text(encoding="utf-8-sig").splitlines():
        match = re.match(r"^\s*(pp_loc_\S+)\s*=\s*\{\s*$", line)
        if not match:
            continue
        modifier = match.group(1)
        if modifier in seen:
            continue
        seen.add(modifier)
        modifiers.append(modifier)
    return modifiers


def _upsert_generated_localization_block(
    path: Path,
    start_marker: str,
    end_marker: str,
    keys_to_remove: Sequence[str],
    lines: Sequence[str],
) -> None:
    if not path.is_file():
        raise SystemExit(f"Cannot inject localization; missing file: {path}")

    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        content = handle.read()
    newline = "\r\n" if "\r\n" in content else "\n"
    block = newline.join(lines) + newline
    pattern = (
        rf"(?ms)^[ \t]*{re.escape(start_marker)}\r?\n"
        rf".*?^[ \t]*{re.escape(end_marker)}\r?\n?"
    )
    existing_block = re.search(pattern, content)
    if existing_block:
        if existing_block.group(0).splitlines() == list(lines):
            return
        content = re.sub(pattern, lambda match: block, content)
    else:
        for key in keys_to_remove:
            content = re.sub(rf'(?m)^[ \t]*{re.escape(key)}:\s*"[^"\r\n]*"\r?\n?', "", content)
        header_pattern = r"(?m)^\ufeff?l_english:\s*\r?\n"
        if not re.search(header_pattern, content):
            raise SystemExit(f"Cannot inject localization; missing l_english header in {path}")
        content = re.sub(header_pattern, lambda match: match.group(0) + block, content, count=1)

    _write_text_if_changed(path, content, encoding="utf-8-sig", newline="")


def _read_text_preserving_newlines(path: Path, *, encoding: str = "utf-8") -> str:
    with path.open("r", encoding=encoding, newline="") as handle:
        return handle.read()


def _write_text_if_changed(
    path: Path,
    text: str,
    *,
    encoding: str = "utf-8",
    newline: str | None = None,
) -> bool:
    wants_bom = encoding.replace("_", "-").lower() == "utf-8-sig"
    if path.exists():
        with path.open("r", encoding=encoding, newline=newline) as handle:
            existing = handle.read()
        has_required_bom = not wants_bom or path.read_bytes().startswith(b"\xef\xbb\xbf")
        if existing == text and has_required_bom:
            return False
    with path.open("w", encoding=encoding, newline=newline) as handle:
        handle.write(text)
    return True


def _analyze(args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path) -> int:
    result = _run(["eu5-orchestrator", "analyze", "--project", project, *extra], repo)
    if result != 0:
        return result
    return _publish_graph_examples(repo, [GOODS_FLOW_EXPLORER.name])


def _output_modifiers(
    args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path
) -> int:
    if extra:
        raise SystemExit("output-modifiers does not accept extra arguments.")

    goods, modifiers, ages = _load_output_modifier_inputs(
        profile=args.profile,
        load_order_path=_repo_path(repo, args.load_order),
    )
    rows = _cumulative_output_modifier_rows(
        goods,
        modifiers,
        ages,
        include_specific=args.include_specific,
    )
    print(_format_output_modifier_table(rows, ages), flush=True)
    return 0


def _load_output_modifier_inputs(
    *,
    profile: str,
    load_order_path: Path,
) -> tuple[list[str], list[dict[str, Any]], list[str]]:
    from eu5gameparser.domain.advancements import load_advancement_data
    from eu5gameparser.domain.availability import AGE_ORDER
    from eu5gameparser.domain.goods import load_goods_data

    goods_data = load_goods_data(profile=profile, load_order_path=load_order_path)
    advancement_data = load_advancement_data(profile=profile, load_order_path=load_order_path)
    goods = sorted(str(row["name"]) for row in goods_data.goods.to_dicts())
    modifiers = _output_modifier_entries(advancement_data.advancements.to_dicts(), list(AGE_ORDER))
    return goods, modifiers, list(AGE_ORDER)


def _output_modifier_entries(
    advancement_rows: Sequence[dict[str, Any]],
    ages: Sequence[str],
) -> list[dict[str, Any]]:
    age_set = set(ages)
    entries: list[dict[str, Any]] = []
    for row in advancement_rows:
        age = row.get("age")
        if age not in age_set:
            continue
        try:
            modifiers = json.loads(row.get("modifiers") or "{}")
        except json.JSONDecodeError:
            continue
        for key, value in modifiers.items():
            if not key.startswith("global_") or not key.endswith("_output_modifier"):
                continue
            if not isinstance(value, int | float) or isinstance(value, bool):
                continue
            entries.append(
                {
                    "good": key.removeprefix("global_").removesuffix("_output_modifier"),
                    "age": age,
                    "value": float(value),
                    "has_potential": bool(row.get("has_potential")),
                }
            )
    return entries


def _cumulative_output_modifier_rows(
    goods: Sequence[str],
    modifiers: Sequence[dict[str, Any]],
    ages: Sequence[str],
    *,
    include_specific: bool,
) -> list[dict[str, Any]]:
    totals = {good: {age: 0.0 for age in ages} for good in goods}
    known_goods = set(goods)
    age_set = set(ages)
    for modifier in modifiers:
        good = str(modifier.get("good") or "")
        age = str(modifier.get("age") or "")
        if not good or age not in age_set:
            continue
        if modifier.get("has_potential") and not include_specific:
            continue
        if good not in totals:
            totals[good] = {known_age: 0.0 for known_age in ages}
            known_goods.add(good)
        totals[good][age] += float(modifier.get("value") or 0.0)

    rows: list[dict[str, Any]] = []
    for good in sorted(known_goods):
        cumulative = 0.0
        row_values: dict[str, float] = {}
        for age in ages:
            cumulative += totals[good][age]
            row_values[age] = cumulative
        rows.append({"good": good, "values": row_values})

    last_age = ages[-1]
    return sorted(rows, key=lambda row: (-row["values"][last_age], row["good"]))


def _format_output_modifier_table(rows: Sequence[dict[str, Any]], ages: Sequence[str]) -> str:
    headers = ["good", *ages]
    formatted_rows = [
        [str(row["good"]), *[_format_modifier_total(row["values"][age]) for age in ages]]
        for row in rows
    ]
    widths = [
        max(len(header), *(len(row[index]) for row in formatted_rows))
        for index, header in enumerate(headers)
    ]
    lines = [
        "  ".join(header.ljust(widths[index]) for index, header in enumerate(headers)),
        "  ".join("-" * width for width in widths),
    ]
    lines.extend(
        "  ".join(value.ljust(widths[index]) for index, value in enumerate(row))
        for row in formatted_rows
    )
    return "\n".join(lines)


def _format_modifier_total(value: float) -> str:
    if abs(value) < 0.0000000001:
        value = 0.0
    return f"{value:.2f}"


def _production_throughput(
    args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path
) -> int:
    if extra:
        raise SystemExit("production-throughput does not accept extra arguments.")

    goods, methods, ages = _load_production_throughput_inputs(
        profile=args.profile,
        load_order_path=_repo_path(repo, args.load_order),
        include_specific=args.include_specific,
    )
    rows = _production_throughput_rows(
        goods,
        methods,
        ages,
        include_specific=args.include_specific,
    )
    print(_format_production_throughput_table(rows, ages), flush=True)
    return 0


def _load_production_throughput_inputs(
    *,
    profile: str,
    load_order_path: Path,
    include_specific: bool,
) -> tuple[list[str], list[dict[str, Any]], list[str]]:
    from eu5gameparser.domain.availability import AGE_ORDER, annotate_building_data_availability
    from eu5gameparser.domain.eu5 import load_eu5_data

    data = load_eu5_data(profile=profile, load_order_path=load_order_path)
    annotated = annotate_building_data_availability(
        data.building_data,
        data.advancements,
        include_specific_unlocks=include_specific,
    )
    goods = sorted(str(row["name"]) for row in data.goods.to_dicts())
    return goods, annotated.production_methods.to_dicts(), list(AGE_ORDER)


def _production_throughput_rows(
    goods: Sequence[str],
    methods: Sequence[dict[str, Any]],
    ages: Sequence[str],
    *,
    include_specific: bool,
) -> list[dict[str, Any]]:
    age_index = {age: index for index, age in enumerate(ages)}
    known_goods = {str(good) for good in goods if str(good)}
    values = {good: {age: 0.0 for age in ages} for good in known_goods}

    for age in ages:
        building_slots: dict[tuple[str, str], dict[object, tuple[float, str]]] = {}
        for method in methods:
            good = str(method.get("produced") or "")
            building = str(method.get("building") or "")
            if not good or not building:
                continue
            if not _production_method_available_by_age(
                method,
                age,
                age_index,
                include_specific=include_specific,
            ):
                continue
            throughput = _production_method_throughput(method)
            if throughput is None:
                continue

            known_goods.add(good)
            values.setdefault(good, {known_age: 0.0 for known_age in ages})
            slot = _production_method_slot(method)
            method_name = str(method.get("name") or "")
            slots = building_slots.setdefault((good, building), {})
            existing = slots.get(slot)
            if (
                existing is None
                or throughput > existing[0]
                or (throughput == existing[0] and method_name < existing[1])
            ):
                slots[slot] = (throughput, method_name)

        best_by_good: dict[str, tuple[float, str]] = {}
        for (good, building), slots in building_slots.items():
            total = sum(throughput for throughput, _name in slots.values())
            existing = best_by_good.get(good)
            if (
                existing is None
                or total > existing[0]
                or (total == existing[0] and building < existing[1])
            ):
                best_by_good[good] = (total, building)

        for good, (total, _building) in best_by_good.items():
            values[good][age] = total

    rows = [{"good": good, "values": values[good]} for good in sorted(known_goods)]
    last_age = ages[-1]
    return sorted(rows, key=lambda row: (-row["values"][last_age], row["good"]))


def _production_method_available_by_age(
    method: dict[str, Any],
    age: str,
    age_index: dict[str, int],
    *,
    include_specific: bool,
) -> bool:
    kind = str(
        method.get("effective_availability_kind")
        or method.get("availability_kind")
        or ""
    )
    if kind == "available_by_default":
        return True
    if kind == "specific_only" and not include_specific:
        return False

    unlock_age = method.get("effective_unlock_age")
    if unlock_age is None:
        unlock_age = method.get("unlock_age")
    unlock_index = age_index.get(str(unlock_age))
    current_index = age_index.get(age)
    return unlock_index is not None and current_index is not None and unlock_index <= current_index


def _production_method_throughput(method: dict[str, Any]) -> float | None:
    if not method.get("input_goods") or not method.get("input_amounts"):
        return None

    input_cost = _positive_float(method.get("input_cost"))
    output_value = _positive_float(method.get("output_value"))
    if input_cost is None or output_value is None:
        return None
    return input_cost + output_value


def _positive_float(value: object) -> float | None:
    if isinstance(value, bool) or value is None:
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(number) or number <= 0.0:
        return None
    return number


def _production_method_slot(method: dict[str, Any]) -> object:
    slot = method.get("production_method_group_index")
    if slot is not None:
        return slot
    return method.get("production_method_group") or "__slotless__"


def _format_production_throughput_table(
    rows: Sequence[dict[str, Any]], ages: Sequence[str]
) -> str:
    return _format_output_modifier_table(rows, ages)


def _savegame(args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path) -> int:
    save_args: list[str | os.PathLike[str]] = []
    if not _has_option(extra, "--save") and not _has_option(extra, "--save-dir"):
        save_args.extend(["--save-dir", _resolve_save_dir(repo, None)])
    result = _run(["eu5-orchestrator", "savegame", "--project", project, *save_args, *extra], repo)
    if result != 0:
        return result
    return _publish_graph_examples(repo, [SAVEGAME_EXPLORER.name])


def _has_option(args: Sequence[str], option: str) -> bool:
    return any(arg == option or arg.startswith(f"{option}=") for arg in args)


def _savegame_purge(args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path) -> int:
    if extra:
        raise SystemExit("savegame-purge does not accept extra arguments.")

    for path in SAVEGAME_PURGE_PATHS:
        target = _repo_path(repo, path)
        if args.dry_run:
            print(f"Would delete: {target}", flush=True)
            continue
        if target.is_dir():
            shutil.rmtree(target)
            print(f"Deleted directory: {target}", flush=True)
        elif target.exists():
            target.unlink()
            print(f"Deleted file: {target}", flush=True)
        else:
            print(f"Already absent: {target}", flush=True)
    return 0


def _publish_docs(
    args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path
) -> int:
    if extra:
        raise SystemExit("publish-docs accepts examples as positional arguments, not extra args.")

    return _publish_graph_examples(repo, args.examples or PUBLISHED_GRAPH_EXAMPLES)


def _publish_graph_examples(repo: Path, examples: Sequence[str]) -> int:
    graphs_dir = repo / "graphs"
    examples_dir = repo / "docs" / "examples"
    examples_dir.mkdir(parents=True, exist_ok=True)

    for example in examples:
        source = graphs_dir / example
        destination = examples_dir / example
        if not source.is_file():
            raise SystemExit(f"Missing generated graph output: {source}")
        shutil.copy2(source, destination)
        print(f"Updated docs/examples/{example}", flush=True)

    graph_assets_dir = graphs_dir / "assets"
    if graph_assets_dir.is_dir():
        example_assets_dir = examples_dir / "assets"
        shutil.copytree(graph_assets_dir, example_assets_dir, dirs_exist_ok=True)
        print("Updated docs/examples/assets", flush=True)
    return 0


def _dashboard(args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path) -> int:
    if extra:
        raise SystemExit("dashboard does not accept extra arguments.")

    dashboard_dir = args.dir if args.dir.is_absolute() else repo / args.dir
    index = dashboard_dir / "index.html"
    if not index.is_file():
        raise SystemExit(
            f"Dashboard index not found: {index}. Generate it first, then rerun `uv run ppc dashboard`."
        )

    url = f"http://{args.host}:{args.port}/"
    print(f"Serving population-capacity dashboard: {url}", flush=True)
    print(f"Dashboard directory: {dashboard_dir}", flush=True)
    _stop_existing_dashboard_processes(
        (
            "http.server",
            str(args.port),
            "--directory",
            str(dashboard_dir),
        )
    )
    return _run(
        [
            sys.executable,
            "-m",
            "http.server",
            str(args.port),
            "--bind",
            args.host,
            "--directory",
            dashboard_dir,
        ],
        repo,
    )


def _savegame_notebooks_build(
    args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path
) -> int:
    if extra:
        raise SystemExit("savegame-notebooks build does not accept extra arguments.")

    active_save_dir: Path | None = None
    if not args.no_ingest:
        save_dir = _resolve_save_dir(repo, args.save_dir)
        active_save_dir = save_dir
        saves = sorted(save_dir.glob("*.eu5")) if save_dir.is_dir() else []
        if not saves:
            raise SystemExit(
                f"No .eu5 saves found in {save_dir}. "
                "Pass --save-dir /path/to/save-games if the EU5 save folder is somewhere else."
            )
        print(f"Found {len(saves)} .eu5 saves in {save_dir}", flush=True)
        ingest_code, ingest_output = _run_collecting_output(
            [
                "uv",
                "run",
                "eu5parse",
                "savegame",
                "ingest",
                "--save-dir",
                save_dir,
                "--output",
                _repo_path(repo, args.dataset),
                "--profile",
                args.profile,
                "--load-order",
                _repo_path(repo, args.load_order),
                "--workers",
                str(args.workers),
            ],
            repo,
        )
        if ingest_code != 0:
            return ingest_code
        processed = _extract_report_count(ingest_output, "processed")
        skipped = _extract_report_count(ingest_output, "skipped")
        if processed == 0:
            suffix = f" ({skipped} already digested)" if skipped is not None else ""
            print(f"raw ingest skipped: no new saves processed{suffix}", flush=True)
        elif processed is not None:
            print(f"raw ingest processed: {processed} new save(s)", flush=True)
    elif args.save_dir is not None:
        active_save_dir = _repo_path(repo, args.save_dir).expanduser()

    _print_savegame_notebook_dataset_status(
        repo,
        _repo_path(repo, args.dataset),
        output=_repo_path(repo, args.output),
        force=args.force,
        active_save_dir=active_save_dir,
        require_manifest=args.no_ingest,
    )
    return 0


def _extract_report_count(output: str, key: str) -> int | None:
    match = re.search(rf"(?m)^{re.escape(key)}:\s*(\d+)\s*$", output)
    return int(match.group(1)) if match else None


def _print_savegame_notebook_dataset_status(
    repo: Path,
    dataset: Path,
    *,
    output: Path,
    force: bool,
    active_save_dir: Path | None,
    require_manifest: bool,
) -> None:
    manifest = dataset / "manifest.parquet"
    if force:
        print("--force ignored: notebooks now read the raw dataset directly.", flush=True)
    if output != repo / SAVEGAME_NOTEBOOK_DATA:
        print(f"--output ignored: notebooks now read {dataset}", flush=True)
    print(f"raw dataset: {dataset}", flush=True)
    print(f"notebook data: {dataset}", flush=True)
    print("notebook rewrite: skipped (not required)", flush=True)
    if not manifest.is_file():
        message = f"raw dataset manifest not found: {manifest}"
        if require_manifest:
            raise SystemExit(message)
        print(message, flush=True)
        return

    try:
        import polars as pl
    except ModuleNotFoundError as exc:
        raise SystemExit(f"Cannot read raw dataset status; missing dependency: {exc.name}") from exc

    frame = pl.read_parquet(manifest)
    total = frame.height
    active = total
    if active_save_dir is not None and not frame.is_empty():
        path_column = (
            "path"
            if "path" in frame.columns
            else "source_path"
            if "source_path" in frame.columns
            else None
        )
        if path_column is not None:
            active = sum(
                1
                for value in frame.get_column(path_column).to_list()
                if _save_path_is_under_active_dir(value, active_save_dir)
            )
    print(f"snapshots: {active}", flush=True)
    if active != total:
        print(f"stale_snapshots_ignored: {total - active}", flush=True)
    table_root = dataset / "tables"
    if table_root.is_dir():
        for table_dir in sorted(path for path in table_root.iterdir() if path.is_dir()):
            count = len(list(table_dir.rglob("*.parquet")))
            if count:
                print(f"{table_dir.name}: {count} parquet file(s)", flush=True)


def _save_path_is_under_active_dir(value: object, active_save_dir: Path) -> bool:
    if value is None:
        return False
    path = Path(str(value)).expanduser()
    try:
        resolved = path.resolve()
    except OSError:
        return False
    if not resolved.is_file():
        return False
    try:
        resolved.relative_to(active_save_dir.expanduser().resolve())
    except ValueError:
        return False
    return True


def _repo_path(repo: Path, path: Path) -> Path:
    return path if path.is_absolute() else repo / path


def _resolve_save_dir(repo: Path, explicit: Path | None) -> Path:
    if explicit is not None:
        return _repo_path(repo, explicit).expanduser()

    checked: list[Path] = []
    for candidate in _savegame_dir_candidates():
        expanded = candidate.expanduser()
        if expanded in checked:
            continue
        checked.append(expanded)
        if expanded.is_dir() and any(expanded.glob("*.eu5")):
            return expanded

    checked_text = "\n".join(f"  - {path}" for path in checked)
    raise SystemExit(
        "Could not auto-detect an EU5 save folder containing .eu5 files. Checked:\n"
        f"{checked_text}\n"
        "Pass --save-dir /path/to/save-games if the save folder is somewhere else."
    )


def _savegame_dir_candidates() -> list[Path]:
    candidates: list[Path] = []
    suffix = Path("Documents/Paradox Interactive/Europa Universalis V/save games")

    for value in (
        os.environ.get("USERPROFILE"),
        _windows_userprofile_from_cmd(),
        Path.home(),
    ):
        if value:
            candidates.append(Path(value) / suffix)

    for base in _wsl_windows_user_dirs():
        candidates.append(base / suffix)
        candidates.append(base / "OneDrive" / suffix)

    return candidates


def _wsl_windows_user_dirs() -> list[Path]:
    users = Path("/mnt/c/Users")
    if not users.is_dir():
        return []
    ignored = {"All Users", "Default", "Default User", "Public", "desktop.ini"}
    return sorted(path for path in users.iterdir() if path.is_dir() and path.name not in ignored)


def _windows_userprofile_from_cmd() -> str | None:
    if shutil.which("cmd.exe") is None:
        return None
    completed = subprocess.run(
        ["cmd.exe", "/c", "echo", "%USERPROFILE%"],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    if completed.returncode != 0:
        return None
    value = completed.stdout.strip()
    if not value or "%" in value:
        return None
    if shutil.which("wslpath") is None:
        return value
    converted = subprocess.run(
        ["wslpath", "-u", value],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    if converted.returncode != 0:
        return value
    return converted.stdout.strip()


def _stop_existing_dashboard_processes(markers: Sequence[str], port: int | None = None) -> None:
    pids = set(_matching_processes(markers))
    if port is not None:
        pids.update(_matching_listening_port_processes(port))

    current_pid = os.getpid()
    pids = sorted(pid for pid in pids if pid != current_pid)
    if not pids:
        return

    print(f"Stopping existing dashboard process(es): {', '.join(str(pid) for pid in pids)}", flush=True)
    for pid in pids:
        _terminate_process(pid, signal.SIGTERM)

    deadline = time.monotonic() + 5
    while time.monotonic() < deadline:
        remaining = [pid for pid in pids if _process_exists(pid)]
        if not remaining:
            return
        time.sleep(0.1)

    kill_signal = getattr(signal, "SIGKILL", signal.SIGTERM)
    for pid in pids:
        if _process_exists(pid):
            _terminate_process(pid, kill_signal)


def _matching_processes(markers: Sequence[str]) -> set[int]:
    if os.name == "nt":
        return _matching_windows_processes(markers)
    return _matching_procfs_processes(markers)


def _matching_listening_port_processes(port: int) -> set[int]:
    if os.name == "nt":
        return _matching_windows_listening_port_processes(port)
    return _matching_procfs_listening_port_processes(port)


def _matching_procfs_processes(markers: Sequence[str]) -> set[int]:
    matches: set[int] = set()
    proc = Path("/proc")
    if not proc.is_dir():
        return matches

    for entry in proc.iterdir():
        if not entry.name.isdigit():
            continue
        try:
            raw = (entry / "cmdline").read_bytes()
        except OSError:
            continue
        command = raw.replace(b"\0", b" ").decode(errors="ignore")
        if command and all(marker in command for marker in markers):
            matches.add(int(entry.name))
    return matches


def _matching_procfs_listening_port_processes(port: int) -> set[int]:
    proc = Path("/proc")
    if not proc.is_dir():
        return set()

    socket_inodes = _listening_socket_inodes(port)
    if not socket_inodes:
        return set()

    matches: set[int] = set()
    for entry in proc.iterdir():
        if not entry.name.isdigit():
            continue
        fd_dir = entry / "fd"
        try:
            fds = list(fd_dir.iterdir())
        except OSError:
            continue
        for fd in fds:
            try:
                target = fd.readlink()
            except OSError:
                continue
            if str(target).startswith("socket:[") and str(target)[8:-1] in socket_inodes:
                matches.add(int(entry.name))
                break
    return matches


def _listening_socket_inodes(port: int) -> set[str]:
    inodes: set[str] = set()
    for table in (Path("/proc/net/tcp"), Path("/proc/net/tcp6")):
        try:
            lines = table.read_text().splitlines()
        except OSError:
            continue
        for line in lines[1:]:
            columns = line.split()
            if len(columns) <= 9:
                continue
            local_address = columns[1]
            state = columns[3]
            inode = columns[9]
            try:
                local_port = int(local_address.rsplit(":", 1)[1], 16)
            except (IndexError, ValueError):
                continue
            if local_port == port and state == "0A" and inode != "0":
                inodes.add(inode)
    return inodes


def _matching_windows_processes(markers: Sequence[str]) -> set[int]:
    command = ["wmic", "process", "get", "ProcessId,CommandLine", "/FORMAT:CSV"]
    completed = subprocess.run(command, check=False, capture_output=True, text=True)
    if completed.returncode != 0:
        return set()

    matches: set[int] = set()
    for line in completed.stdout.splitlines():
        if not line.strip() or line.startswith("Node,"):
            continue
        try:
            command_line, pid = line.rsplit(",", 1)
            pid_value = int(pid)
        except ValueError:
            continue
        if all(marker in command_line for marker in markers):
            matches.add(pid_value)
    return matches


def _matching_windows_listening_port_processes(port: int) -> set[int]:
    completed = subprocess.run(
        ["netstat", "-ano", "-p", "tcp"],
        check=False,
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        return set()

    matches: set[int] = set()
    for line in completed.stdout.splitlines():
        columns = line.split()
        if len(columns) < 5 or columns[0].upper() != "TCP":
            continue
        local_address, state, pid = columns[1], columns[3], columns[4]
        if state.upper() != "LISTENING":
            continue
        try:
            local_port = int(local_address.rsplit(":", 1)[1])
            pid_value = int(pid)
        except (IndexError, ValueError):
            continue
        if local_port == port:
            matches.add(pid_value)
    return matches


def _terminate_process(pid: int, sig: signal.Signals) -> None:
    try:
        os.kill(pid, sig)
    except ProcessLookupError:
        return
    except PermissionError as error:
        print(f"Could not stop dashboard process {pid}: {error}", flush=True)


def _process_exists(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def _sync_stage_fingerprints(repo: Path, project: Path) -> dict[str, str]:
    config = _project_config(project)
    return {
        "labeling": _fingerprint_paths(_labeling_fingerprint_paths(repo, project, config)),
        "blueprints": _fingerprint_paths(_blueprint_fingerprint_paths(repo, project, config)),
        "population_capacity": _fingerprint_paths(_population_capacity_fingerprint_paths(repo, project, config)),
    }


def _labeling_fingerprint_paths(repo: Path, project: Path, config: dict[str, Any]) -> list[Path]:
    paths = [project, repo / CONSTRUCTOR_LOAD_ORDER]
    labeling = _mapping(config.get("labeling", {}))
    if labeling.get("enabled", True) is False:
        return paths
    label_config = _config_path(repo, labeling.get("config"))
    if label_config is None:
        return paths
    paths.append(label_config)
    population = _mapping(config.get("population_capacity", {}))
    if population.get("enabled", True) is not False:
        population_config = _config_path(repo, population.get("config"))
        if population_config is not None:
            paths.append(population_config)
    if not label_config.is_file():
        return paths
    raw = _load_yaml_mapping(label_config)
    paths.extend(
        _existing_config_paths(
            label_config.parent,
            raw,
            ("baseline_parquet", "template_dir"),
        )
    )
    for good in raw.get("goods", []) or []:
        if not isinstance(good, dict) or good.get("enabled", True) is False:
            continue
        evaluator = good.get("evaluator_config")
        if evaluator is None:
            continue
        evaluator_path = _resolve_config_path(label_config.parent, evaluator)
        paths.append(evaluator_path)
        paths.extend(_evaluator_fingerprint_paths(evaluator_path))
    return paths


def _evaluator_fingerprint_paths(evaluator_path: Path) -> list[Path]:
    if not evaluator_path.is_file():
        return []
    raw = _load_yaml_mapping(evaluator_path)
    trade_good = str(raw.get("trade_good", raw.get("tradeGood", "good")) or "good").strip() or "good"
    goods_data_dir = raw.get("goods_data_dir") or f"../../goods_data/{trade_good}"
    runs_filename = raw.get("runs_filename", raw.get("runsFilename")) or f"{trade_good}_ranking_runs.parquet"
    results_filename = raw.get("results_filename", raw.get("resultsFilename")) or f"{trade_good}_labels.parquet"
    dealbreaker = raw.get("dealbreaker_rules_csv", raw.get("dealbreakerRulesCsv", "dealbreakers.csv"))
    return [
        _resolve_config_path(evaluator_path.parent, raw.get("baseline_parquet") or "../../base_data/locations_with_raw_material.parquet"),
        _resolve_config_path(evaluator_path.parent, dealbreaker),
        _resolve_config_path(evaluator_path.parent, goods_data_dir) / str(runs_filename),
        _resolve_config_path(evaluator_path.parent, goods_data_dir) / str(results_filename),
    ]


def _blueprint_fingerprint_paths(repo: Path, project: Path, config: dict[str, Any]) -> list[Path]:
    blueprints = _mapping(config.get("building_blueprints", {}))
    manifest = _config_path(repo, blueprints.get("manifest")) or repo / "blueprints" / "buildings.manifest.yml"
    return [project, manifest, repo / "blueprints" / "accepted"]


def _population_capacity_fingerprint_paths(repo: Path, project: Path, config: dict[str, Any]) -> list[Path]:
    population = _mapping(config.get("population_capacity", {}))
    paths = [project]
    if population.get("enabled", True) is False:
        return paths
    population_config = _config_path(repo, population.get("config")) or repo / "population_capacity.toml"
    paths.append(population_config)
    return paths


def _validation_fingerprint(repo: Path, project: Path) -> str:
    mod_root = _project_mod_root(repo, project)
    return _fingerprint_paths(
        [project, repo / CONSTRUCTOR_LOAD_ORDER, mod_root],
        file_filter=_is_validation_input,
    )


def _is_validation_input(path: Path) -> bool:
    return path.suffix.lower() in {".txt", ".yml", ".yaml", ".gui"}


def _fingerprint_paths(paths: Sequence[Path], *, file_filter=None) -> str:
    digest = hashlib.sha256()
    for path in sorted({item.resolve() if item.exists() else item for item in paths}, key=str):
        _fingerprint_path(digest, path, path, file_filter=file_filter)
    return digest.hexdigest()


def _fingerprint_path(digest, path: Path, root: Path, *, file_filter=None) -> None:
    if path.is_dir():
        files = sorted(candidate for candidate in path.rglob("*") if candidate.is_file())
        for candidate in files:
            if file_filter is not None and not file_filter(candidate):
                continue
            _fingerprint_file(digest, candidate, candidate.relative_to(root))
        return
    if not path.is_file():
        digest.update(f"missing:{path}\n".encode("utf-8", errors="surrogateescape"))
        return
    if file_filter is None or file_filter(path):
        _fingerprint_file(digest, path, Path(path.name))


def _fingerprint_file(digest, path: Path, label: Path) -> None:
    digest.update(str(label).replace(os.sep, "/").encode("utf-8", errors="surrogateescape"))
    digest.update(b"\0")
    digest.update(path.read_bytes())
    digest.update(b"\0")


def _project_config(project: Path) -> dict[str, Any]:
    with project.open("rb") as handle:
        return tomllib.load(handle)


def _mapping(value: object) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _config_path(repo: Path, value: object) -> Path | None:
    if value in (None, ""):
        return None
    return _resolve_config_path(repo, value)


def _existing_config_paths(base: Path, raw: dict[str, Any], keys: Sequence[str]) -> list[Path]:
    paths = []
    for key in keys:
        value = raw.get(key)
        if value not in (None, ""):
            paths.append(_resolve_config_path(base, value))
    return paths


def _resolve_config_path(base: Path, value: object) -> Path:
    path = Path(str(value))
    return path if path.is_absolute() else (base / path).resolve()


def _load_yaml_mapping(path: Path) -> dict[str, Any]:
    import yaml

    raw = yaml.safe_load(path.read_text(encoding="utf-8-sig"))
    return raw if isinstance(raw, dict) else {}


def _load_sync_state(repo: Path) -> dict[str, str]:
    path = repo / SYNC_STATE_PATH
    if not path.is_file():
        return {}
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        return {}
    return {str(key): str(value) for key, value in raw.items() if isinstance(value, str)}


def _save_sync_state(repo: Path, state: dict[str, str]) -> None:
    path = repo / SYNC_STATE_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _record_current_sync_state(repo: Path, project: Path) -> None:
    state = _sync_stage_fingerprints(repo, project)
    state["validation"] = _validation_fingerprint(repo, project)
    _save_sync_state(repo, state)


def _deploy_built_mod(repo: Path, project: Path, *, force: bool) -> int:
    command: list[str | os.PathLike[str]] = ["eu5-orchestrator", "deploy", "--project", project, "--clean"]
    if force:
        command.append("--force")
    return _run(command, repo)


def _smart_sync(args: argparse.Namespace, repo: Path, project: Path) -> int:
    state = _load_sync_state(repo)
    fingerprints = _sync_stage_fingerprints(repo, project)
    ran_generator = False
    commands: dict[str, list[str | os.PathLike[str]]] = {
        "labeling": ["eu5-orchestrator", "label", "--project", project],
        "blueprints": ["eu5-orchestrator", "render", "--project", project, "--overwrite"],
        "population_capacity": ["eu5-orchestrator", "population-capacity", "render", "--project", project],
    }

    for stage in SYNC_STAGES:
        if not args.force_build and state.get(stage) == fingerprints[stage]:
            print(f"Smart sync: {stage} inputs unchanged; skipping.", flush=True)
            continue
        result = _run(commands[stage], repo)
        if result != 0:
            return result
        state[stage] = fingerprints[stage]
        ran_generator = True

    if ran_generator:
        _finalize_constructor_mod(repo, project)

    validation_before = _validation_fingerprint(repo, project)
    if ran_generator or args.force_build or state.get("validation") != validation_before:
        result = _run(["eu5-orchestrator", "validate", "--project", project], repo)
        if result != 0:
            return result
        state["validation"] = _validation_fingerprint(repo, project)
    else:
        print("Smart sync: validation inputs unchanged; skipping validation.", flush=True)

    _save_sync_state(repo, state)
    return _deploy_built_mod(repo, project, force=args.force_deploy)


def _sync(args: argparse.Namespace, extra: Sequence[str], repo: Path, project: Path) -> int:
    if extra:
        raise SystemExit("sync does not accept extra arguments.")
    if not args.yes:
        raise SystemExit(
            "Refusing to mirror into the live Paradox mod folder without explicit confirmation. "
            "Re-run `uv run ppc sync --yes` only when you intend to update the live mod."
        )
    if not (repo / "constructor.local.toml").is_file():
        raise SystemExit(
            "Refusing to sync: constructor.local.toml is missing. Configure [deploy].target first."
        )
    if args.full_build:
        build_result = _build(args, (), repo, project)
        if build_result != 0:
            return build_result
        _record_current_sync_state(repo, project)
        return _deploy_built_mod(repo, project, force=args.force_deploy)
    return _smart_sync(args, repo, project)


if __name__ == "__main__":
    raise SystemExit(main())
