from __future__ import annotations

import re
import shutil
import tomllib
from pathlib import Path
from typing import Iterable

from eu5gameparser.domain.eu5 import load_eu5_data


ROOT = Path(__file__).resolve().parents[1]
PROJECT_CONFIG = ROOT / "constructor.toml"

MAP_MODE_REL = Path("in_game/gfx/map/map_modes/pp_local_output_modifier_map_modes.txt")
LOCALIZATION_REL = Path("main_menu/localization/english/pp_building_adjustments_l_english.yml")
IN_GAME_ICON_REL = Path("in_game/gfx/interface/icons/map_modes")
MAIN_MENU_ICON_REL = Path("main_menu/gfx/interface/icons/map_modes")
TRADE_GOOD_ICON_REL = Path("main_menu/gfx/interface/icons/trade_goods")

LOCALIZATION_START = "  # Local output modifier map modes (pp_local_output_modifier_map_modes.txt)"
LOCALIZATION_END = "  # End generated local output modifier map modes"


def main() -> None:
    project = _load_project_config(PROJECT_CONFIG)
    mod_root = _project_path(project["project"]["mod_root"])
    raw_materials = _raw_material_goods(project)

    _write_map_modes(mod_root / MAP_MODE_REL, raw_materials)
    _upsert_localization(mod_root / LOCALIZATION_REL, raw_materials)
    _ensure_icons(mod_root, raw_materials, project)
    print(f"Generated local output modifier map modes for {len(raw_materials)} raw materials.")


def _load_project_config(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def _project_path(raw: str) -> Path:
    path = Path(raw)
    return path if path.is_absolute() else (ROOT / path).resolve()


def _raw_material_goods(project: dict) -> list[str]:
    parser = project.get("parser", {})
    profile = str(parser.get("profile") or "constructor")
    load_order = _project_path(str(parser.get("load_order") or "constructor.load_order.toml"))
    data = load_eu5_data(profile=profile, load_order_path=load_order)
    return (
        data.goods.filter(data.goods["category"] == "raw_material")
        .select("name")
        .to_series()
        .to_list()
    )


def _vanilla_root(project: dict) -> Path:
    parser = project.get("parser", {})
    load_order = _project_path(str(parser.get("load_order") or "constructor.load_order.toml"))
    with load_order.open("rb") as stream:
        raw = tomllib.load(stream)
    paths = raw.get("paths", {})
    vanilla_root = Path(str(paths.get("vanilla_root", "")))
    if not vanilla_root.is_absolute():
        vanilla_root = (load_order.parent / vanilla_root).resolve()
    return vanilla_root


def _write_map_modes(path: Path, goods: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    blocks = [
        "# Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand.",
        "# Displays local_<good>_output_modifier for every parsed raw_material good.",
        "# Red = -50%, Green = +150%. Values are additive percentages (0.1 = +10%).",
        "# Geography index = 2 keeps these in the terrain/climate bucket.",
        "",
        "@factor_add = 0.5",
        "@factor_divide = 2.0",
        "@zoom_step_near = 2",
        "@data_gradient_alpha_inside = 1",
        "@data_gradient_alpha_outside = 1",
        "@data_gradient_width = 0.25",
        "@data_gradient_color_mult = 0.9",
        "@data_edge_width = 0",
        "@data_edge_sharpness = 0.01",
        "@data_edge_alpha = 0",
        "@data_edge_color_mult = 0",
        "@data_before_lighting_blend = 0.5",
        "@data_after_lighting_blend = 0.5",
        "",
    ]
    for good in goods:
        blocks.append(_map_mode_block(good))
    path.write_text("\n".join(blocks).rstrip() + "\n", encoding="utf-8-sig")


def _map_mode_block(good: str) -> str:
    upper = good.upper()
    return f"""pp_local_{good}_output_modifier = {{
\tmap_color = {{
\t\tif = {{
\t\t\tlimit = {{ is_ownable = yes }}
\t\t\tlerp = {{
\t\t\t\tmin_color = define:NMapColors|MAP_COLOR_LOW
\t\t\t\tmax_color = define:NMapColors|MAP_COLOR_HIGH
\t\t\t\tfactor = {{
\t\t\t\t\tvalue = modifier:local_{good}_output_modifier
\t\t\t\t\tadd = @factor_add
\t\t\t\t\tdivide = @factor_divide
\t\t\t\t}}
\t\t\t}}
\t\t}}
\t\telse = {{ value = rgb {{ 128 128 128 }} }}
\t}}
\tlegend_key = {{ desc = "MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER" color = define:NMapColors|MAP_COLOR_HIGH }}
\ttooltip_key = {{
\t\tif = {{
\t\t\tlimit = {{ is_land = yes }}
\t\t\tvalue = MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_TT_LAND_BREAKDOWN
\t\t}}
\t\telse = {{
\t\t\tvalue = MAPMODE_PP_LOCAL_OUTPUT_TT_WATER
\t\t}}
\t}}
\tsmall_map_names = location
\tmedium_map_names = location
\tlarge_map_names = location
\tsmall_tooltip_context = location
\tmedium_tooltip_context = location
\tlarge_tooltip_context = location
\tfill_in_impassable = yes
\tenable_snow = no
\tflatmap_behaviour = always
\tuse_fow = no
\tcategory = geography
\tindex = 2
\tallow_allocate_hotkey = no
\tmap_markers = {{ all = no }}
\tgradient_parameters = {{
\t\tzoom_step = @zoom_step_near
\t\tgradient_alpha_inside = @data_gradient_alpha_inside
\t\tgradient_alpha_outside = @data_gradient_alpha_outside
\t\tgradient_width = @data_gradient_width
\t\tgradient_color_mult = @data_gradient_color_mult
\t\tedge_width = @data_edge_width
\t\tedge_sharpness = @data_edge_sharpness
\t\tedge_alpha = @data_edge_alpha
\t\tedge_color_mult = @data_edge_color_mult
\t\tbefore_lighting_blend = @data_before_lighting_blend
\t\tafter_lighting_blend = @data_after_lighting_blend
\t}}
}}
"""


def _upsert_localization(path: Path, goods: Iterable[str]) -> None:
    existing = path.read_text(encoding="utf-8-sig")
    generated = _localization_block(goods)
    if LOCALIZATION_START in existing:
        if LOCALIZATION_END in existing:
            pattern = re.compile(
                rf"{re.escape(LOCALIZATION_START)}.*?{re.escape(LOCALIZATION_END)}\n?",
                re.DOTALL,
            )
            updated = pattern.sub(lambda _match: generated, existing)
        else:
            legacy_end = re.compile(
                rf"{re.escape(LOCALIZATION_START)}.*?"
                r'  MAPMODE_PP_LOCAL_OUTPUT_TT_WATER: "[^"]*"\n?',
                re.DOTALL,
            )
            updated = legacy_end.sub(lambda _match: generated, existing)
    else:
        anchor = "  # Unemployed Peasants (Unemployment) map mode - absolute numbers, cap 0-50k"
        if anchor not in existing:
            raise ValueError(f"Could not find localization insertion point in {path}")
        updated = existing.replace(anchor, generated + "\n" + anchor)
    path.write_text(updated.rstrip() + "\n", encoding="utf-8-sig")


def _localization_block(goods: Iterable[str]) -> str:
    lines = [
        LOCALIZATION_START,
        "  # Generated by scripts/generate_raw_material_local_map_modes.py - do not edit by hand.",
        '  PP_LOCAL_OUTPUT_MAPMODE_RANGE: "Red=-50%, Green=150%"',
    ]
    goods = list(goods)
    for good in goods:
        lines.append(f'  mapmode_pp_local_{good}_output_modifier_name: "Local {_display_name(good)} Output"')
    lines.append("")
    for good in goods:
        upper = good.upper()
        name_key = f"mapmode_pp_local_{good}_output_modifier_name"
        lines.append(
            f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER: "#T ${name_key}$#!\\n'
            f'This colors [locations|e] by the local {_display_name(good).lower()} output modifier in the [location|e]."'
        )
    lines.append("")
    for good in goods:
        upper = good.upper()
        display = _display_name(good).lower()
        lines.append(
            f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_TT_LAND: '
            f'"[ROOT.GetLocation.GetName] has a local {display} output modifier of '
            f"[ROOT.GetLocation.GetModifierValue('local_{good}_output_modifier')|Y].\""
        )
    lines.append("")
    for good in goods:
        upper = good.upper()
        display = _display_name(good).lower()
        lines.append(
            f'  MAPMODE_PP_LOCAL_{upper}_OUTPUT_MODIFIER_TT_LAND_BREAKDOWN: '
            f'"[ROOT.GetLocation.GetName] has a local {display} output modifier of '
            f"[ROOT.GetLocation.GetModifierValue('local_{good}_output_modifier')|Y].\\n"
            'Aggregated from vegetation, topography, climate, water, and labeling sources."'
        )
    lines.extend(
        [
            "",
            '  MAPMODE_PP_LOCAL_OUTPUT_TT_WATER: "[ROOT.GetLocation.GetName] is not a land [location|e] so it does not have production modifiers."',
            LOCALIZATION_END,
        ]
    )
    return "\n".join(lines) + "\n"


def _display_name(good: str) -> str:
    return good.replace("_", " ").title()


def _ensure_icons(mod_root: Path, goods: Iterable[str], project: dict) -> None:
    vanilla_root = _vanilla_root(project)
    targets = [mod_root / IN_GAME_ICON_REL, mod_root / MAIN_MENU_ICON_REL]
    for target in targets:
        target.mkdir(parents=True, exist_ok=True)

    missing: list[str] = []
    for good in goods:
        source = _icon_source(mod_root, vanilla_root, good)
        if source is None:
            missing.append(good)
            continue
        for target_dir in targets:
            destination = target_dir / f"pp_local_{good}_output_modifier.dds"
            if not destination.exists():
                shutil.copy2(source, destination)
    if missing:
        raise FileNotFoundError("Missing icon source for raw material goods: " + ", ".join(missing))


def _icon_source(mod_root: Path, vanilla_root: Path, good: str) -> Path | None:
    candidates = [
        mod_root / IN_GAME_ICON_REL / f"pp_local_{good}_output_modifier.dds",
        mod_root / MAIN_MENU_ICON_REL / f"pp_local_{good}_output_modifier.dds",
        mod_root / IN_GAME_ICON_REL / f"pp_{good}_output.dds",
        mod_root / MAIN_MENU_ICON_REL / f"pp_{good}_output.dds",
        vanilla_root / "game" / TRADE_GOOD_ICON_REL / f"icon_goods_{good}.dds",
        mod_root / TRADE_GOOD_ICON_REL / f"icon_goods_{good}.dds",
        mod_root / "in_game" / "gfx" / "interface" / "icons" / "trade_goods" / f"icon_goods_{good}.dds",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return None


if __name__ == "__main__":
    main()
