from __future__ import annotations

import argparse
import json
import re
import tomllib
from pathlib import Path
from typing import Iterable

from eu5gameparser.domain.eu5 import load_eu5_data

from map_mode_styles import CALIBRATION_PATH


ROOT = Path(__file__).resolve().parents[1]
PROJECT_CONFIG = ROOT / "constructor.toml"
MOD_ROOT_DEFAULT = ROOT / "mod" / "Prosper or Perish (Population Growth & Food Rework)"
LOCATION_MODIFIERS_REL = Path("main_menu/common/static_modifiers/pp_location_modifiers.txt")
BUILDING_CAPACITY_VALUES_REL = Path("in_game/common/script_values/pp_building_capacity_values.txt")
BUILDING_CAPS_REL = Path("in_game/common/script_values/pp_building_caps.txt")


def main() -> None:
    parser = argparse.ArgumentParser(description="Calibrate custom map-mode bucket thresholds.")
    parser.add_argument("--write", action="store_true", help="Write the calibration JSON.")
    parser.add_argument("--path", type=Path, default=CALIBRATION_PATH, help="Output calibration path.")
    args = parser.parse_args()

    calibration = build_calibration()
    text = json.dumps(calibration, indent=2, sort_keys=True) + "\n"
    if args.write:
        args.path.parent.mkdir(parents=True, exist_ok=True)
        args.path.write_text(text, encoding="utf-8")
        print(f"Wrote {args.path.relative_to(ROOT)}")
    else:
        print(text, end="")


def build_calibration() -> dict:
    project = _load_project_config(PROJECT_CONFIG)
    mod_root = _project_path(project["project"].get("mod_root", str(MOD_ROOT_DEFAULT)))
    goods = sorted(_all_goods(project))
    raw_materials = _raw_material_goods(project)

    goods_samples = _goods_output_samples()
    local_output_samples = _local_output_modifier_samples(mod_root / LOCATION_MODIFIERS_REL)
    food_capacity_samples = _food_capacity_samples(mod_root)

    return {
        "schema_version": 1,
        "notes": [
            "Generated by tools/calibrate_pp_map_mode_scales.py.",
            "Thresholds are build-time calibration data for bucketed EU5 map modes.",
        ],
        "scales": {
            "goods_output": {
                good: _sequential_scale_dict(_positive_quantity_thresholds(goods_samples.get(good, [])))
                for good in goods
            },
            "local_output_modifier": {
                good: _signed_scale_dict(local_output_samples.get(good, []))
                for good in raw_materials
            },
            "market_food_price": _reference_scale_dict(_market_food_price_values()),
            "food_capacity": {
                "fish": _sequential_scale_dict(_food_capacity_thresholds("fish", food_capacity_samples.get("fish", []))),
                "farm": _sequential_scale_dict(_food_capacity_thresholds("farm", food_capacity_samples.get("farm", []))),
                "forest": _sequential_scale_dict(_food_capacity_thresholds("forest", food_capacity_samples.get("forest", []))),
            },
            "population_capacity": _sequential_scale_dict(
                _positive_quantity_thresholds(_population_capacity_values(mod_root / LOCATION_MODIFIERS_REL))
            ),
            "population_growth": {
                "kind": "signed_centered",
                "negative_thresholds": [-0.007, -0.002],
                "neutral_low": -0.0005,
                "neutral_high": 0.0005,
                "positive_thresholds": [0.00375, 0.009],
                "source": "static_growth_modifier_anchors",
            },
            "unemployment": _sequential_scale_dict(_positive_quantity_thresholds(_unemployment_values())),
            "building_levels": _sequential_scale_dict(_positive_quantity_thresholds(_building_level_values())),
            "rgo_level": _sequential_scale_dict(_rgo_level_thresholds(_rgo_level_values())),
        },
    }


def _load_project_config(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def _project_path(raw: str) -> Path:
    match = re.match(r"^([A-Za-z]):[\\/](.*)$", raw)
    if match is not None:
        return Path("/mnt") / match.group(1).lower() / match.group(2).replace("\\", "/")
    path = Path(raw)
    return path if path.is_absolute() else (ROOT / path).resolve()


def _all_goods(project: dict) -> list[str]:
    data = _load_parser_data(project)
    return data.goods.select("name").to_series().to_list()


def _raw_material_goods(project: dict) -> list[str]:
    data = _load_parser_data(project)
    return (
        data.goods.filter(data.goods["category"] == "raw_material")
        .select("name")
        .to_series()
        .to_list()
    )


def _load_parser_data(project: dict):
    parser = project.get("parser", {})
    profile = str(parser.get("profile") or "constructor")
    load_order = _project_path(str(parser.get("load_order") or "constructor.load_order.toml"))
    return load_eu5_data(profile=profile, load_order_path=load_order)


def _goods_output_samples() -> dict[str, list[float]]:
    try:
        import polars as pl
    except ImportError:
        return {}

    sample_frames = []
    for path in (
        ROOT / "artifacts" / "data" / "savegame" / "production_method_good_flows.parquet",
        ROOT / "artifacts" / "data" / "savegame" / "rgo_flows.parquet",
    ):
        if not path.exists():
            continue
        flow = pl.read_parquet(path)
        sample_frames.append(
            flow.filter(
                (pl.col("direction") == "output")
                & (pl.col("save_side") == "supplied_Production")
                & (pl.col("nominal_amount") > 0)
            )
            .group_by(["good_id", "location_id"])
            .agg(pl.col("nominal_amount").sum().alias("output"))
        )

    if not sample_frames:
        return {}

    samples = pl.concat(sample_frames, how="vertical_relaxed").group_by(["good_id", "location_id"]).agg(
        pl.col("output").sum().alias("output")
    )
    return {
        row["good_id"]: row["outputs"]
        for row in samples.group_by("good_id")
        .agg(pl.col("output").sort().alias("outputs"))
        .to_dicts()
    }


def _local_output_modifier_samples(path: Path) -> dict[str, list[float]]:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8-sig")
    samples: dict[str, list[float]] = {}
    for good, value in re.findall(
        r"^\s*local_([a-z0-9_]+)_output_modifier\s*=\s*([-+]?\d+(?:\.\d+)?)\s*$",
        text,
        flags=re.MULTILINE,
    ):
        samples.setdefault(good, []).append(float(value))
    return samples


def _population_capacity_values(path: Path) -> list[float]:
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8-sig")
    return [
        float(value)
        for value in re.findall(r"^\s*local_population_capacity\s*=\s*([-+]?\d+(?:\.\d+)?)\s*$", text, flags=re.MULTILINE)
    ]


def _market_food_price_values() -> list[float]:
    try:
        import polars as pl
    except ImportError:
        return []
    path = ROOT / "artifacts" / "data" / "savegame" / "market_food.parquet"
    if not path.exists():
        return []
    return pl.read_parquet(path).filter(pl.col("food_price") > 0)["food_price"].to_list()


def _unemployment_values() -> list[float]:
    try:
        import polars as pl
    except ImportError:
        return []
    path = ROOT / "artifacts" / "data" / "savegame" / "locations.parquet"
    if not path.exists():
        return []
    return (pl.read_parquet(path)["unemployed_total"] * 1000).to_list()


def _building_level_values() -> list[float]:
    try:
        import polars as pl
    except ImportError:
        return []
    path = ROOT / "artifacts" / "data" / "savegame" / "buildings.parquet"
    if not path.exists():
        return []
    rows = (
        pl.read_parquet(path)
        .group_by("location_id")
        .agg(pl.col("level").sum().alias("total_building_levels"))
        .filter(pl.col("total_building_levels") > 0)
    )
    return rows["total_building_levels"].to_list()


def _rgo_level_values() -> list[float]:
    try:
        import polars as pl
    except ImportError:
        return []
    path = ROOT / "artifacts" / "data" / "savegame" / "locations.parquet"
    if not path.exists():
        return []
    return pl.read_parquet(path).filter(pl.col("max_raw_material_workers") > 0)["max_raw_material_workers"].to_list()


def _food_capacity_samples(mod_root: Path) -> dict[str, list[float]]:
    try:
        import polars as pl
    except ImportError:
        return {}
    locations_path = ROOT / "artifacts" / "data" / "savegame" / "locations.parquet"
    buildings_path = ROOT / "artifacts" / "data" / "savegame" / "buildings.parquet"
    if not locations_path.exists() or not buildings_path.exists():
        return {}

    caps_text = (mod_root / BUILDING_CAPS_REL).read_text(encoding="utf-8-sig")
    values_text = (mod_root / BUILDING_CAPACITY_VALUES_REL).read_text(encoding="utf-8-sig")
    farm_goods = _goods_in_script_value(values_text, "pp_farm_base_capacity_value")
    forest_goods = _goods_in_script_value(values_text, "pp_forest_base_capacity_value")
    farm_buildings = _building_types_in_script_value(caps_text, "land_farm_building_levels")
    fish_buildings = _building_types_in_script_value(caps_text, "fish_building_levels")
    forest_buildings = _building_types_in_script_value(caps_text, "forest_building_levels")
    population_capacity = _population_capacity_by_slug(mod_root / LOCATION_MODIFIERS_REL)

    buildings = pl.read_parquet(buildings_path)
    total_levels = _levels_by_location(buildings)
    farm_levels = _levels_by_location(buildings.filter(pl.col("building_type").is_in(farm_buildings)))
    fish_levels = _levels_by_location(buildings.filter(pl.col("building_type").is_in(fish_buildings)))
    forest_levels = _levels_by_location(buildings.filter(pl.col("building_type").is_in(forest_buildings)))

    samples = {"farm": [], "fish": [], "forest": []}
    for row in pl.read_parquet(locations_path).to_dicts():
        location_id = row["location_id"]
        raw_material = str(row.get("raw_material") or "")
        max_rgo = float(row.get("max_raw_material_workers") or 0)
        total = total_levels.get(location_id, 0.0)
        farm_used = farm_levels.get(location_id, 0.0)
        fish_used = fish_levels.get(location_id, 0.0)
        forest_used = forest_levels.get(location_id, 0.0)
        non_farm = max(total - farm_used, 0.0)
        non_forest = max(total - forest_used, 0.0)
        pop_capacity = population_capacity.get(str(row.get("slug") or ""), 0.0)

        farm_base = 4.0 if raw_material in farm_goods else 0.0
        farm = farm_base + (farm_base * max_rgo * 0.125) + (pop_capacity * 0.08) - (non_farm * 0.05) - farm_used
        samples["farm"].append(max(farm, 0.0))

        fish_base = 3.0 if raw_material == "fish" else 0.0
        fish = fish_base + (fish_base * max_rgo * 0.030) - fish_used
        samples["fish"].append(max(fish, 0.0))

        forest_base = 4.4 if raw_material in forest_goods else 0.0
        forest = forest_base + (forest_base * max_rgo * 0.030) - (non_forest * 0.1) - forest_used
        samples["forest"].append(max(forest, 0.0))

    return samples


def _levels_by_location(frame) -> dict[int, float]:
    import polars as pl

    return {
        row["location_id"]: float(row["level"])
        for row in frame.group_by("location_id").agg(pl.col("level").sum()).to_dicts()
    }


def _goods_in_script_value(text: str, name: str) -> set[str]:
    body = _script_value_body(text, name)
    return set(re.findall(r"raw_material\s*=\s*goods:([a-z0-9_]+)", body))


def _building_types_in_script_value(text: str, name: str) -> set[str]:
    body = _script_value_body(text, name)
    return set(re.findall(r"location_building_level\(building_type:([a-z0-9_]+)\)", body))


def _script_value_body(text: str, name: str) -> str:
    match = re.search(rf"^{re.escape(name)}\s*=\s*\{{(?P<body>.*?)(?=^[a-zA-Z0-9_]+\s*=\s*\{{|\Z)", text, flags=re.DOTALL | re.MULTILINE)
    return match.group("body") if match is not None else ""


def _population_capacity_by_slug(path: Path) -> dict[str, float]:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8-sig")
    result: dict[str, float] = {}
    for match in re.finditer(r"^pp_loc_([a-z0-9_]+)\s*=\s*\{(?P<body>.*?)(?=^pp_loc_|\Z)", text, flags=re.DOTALL | re.MULTILINE):
        value_match = re.search(r"^\s*local_population_capacity\s*=\s*([-+]?\d+(?:\.\d+)?)\s*$", match.group("body"), flags=re.MULTILINE)
        if value_match is not None:
            result[match.group(1)] = float(value_match.group(1))
    return result


def _positive_quantity_thresholds(values: Iterable[float]) -> list[float]:
    positives = sorted(float(value) for value in values if float(value) > 0)
    if len(positives) < 5:
        return [0.25, 1.0, 4.0, 16.0]
    raw = [_quantile(positives, quantile) for quantile in (0.20, 0.45, 0.70, 0.95)]
    rounded = [_round_quantity(value) for value in raw]
    candidates = sorted({_round_quantity(value) for value in positives if value > 0})
    return _strict_thresholds_from_candidates(rounded, candidates, minimum=0.01)


def _food_capacity_thresholds(capacity: str, values: Iterable[float]) -> list[float]:
    thresholds = _positive_quantity_thresholds(values)
    if capacity == "farm":
        # Farm capacity receives live location, improvement, and water-control bonuses
        # that are underrepresented in the static/savegame sample. Keep the lower
        # dynamic breaks, but reserve enough high-end range for developed farms.
        return [
            max(thresholds[0], 1.0),
            max(thresholds[1], 4.0),
            max(thresholds[2], 12.0),
            max(thresholds[3], 24.0),
        ]
    if min(right - left for left, right in zip(thresholds, thresholds[1:])) >= 0.25:
        return thresholds
    fallback = {
        "fish": [1.5, 3.0, 4.5, 9.0],
        "farm": [1.0, 3.5, 6.0, 10.0],
        "forest": [3.3, 4.4, 6.6, 11.0],
    }
    return fallback[capacity]


def _rgo_level_thresholds(values: Iterable[float]) -> list[float]:
    positives = sorted(float(value) for value in values if float(value) > 0)
    unique_levels = sorted({round(value) for value in positives if abs(value - round(value)) < 0.001})
    if len(unique_levels) >= 4:
        return [float(value) for value in unique_levels[:4]]
    return _positive_quantity_thresholds(positives)


def _signed_output_scale_thresholds(values: Iterable[float]) -> dict[str, object]:
    numbers = [float(value) for value in values]
    negatives = sorted(value for value in numbers if value < -0.05)
    positives = sorted(value for value in numbers if value > 0.05)

    if len(negatives) >= 5:
        negative = [_round_modifier(_quantile(negatives, 0.20)), _round_modifier(_quantile(negatives, 0.70))]
        negative = [min(negative[0], -0.06), min(negative[1], -0.051)]
        if not negative[0] < negative[1]:
            negative = [-0.70, -0.25]
    else:
        negative = [-0.70, -0.25]

    if len(positives) >= 5:
        positive = [
            _round_modifier(_quantile(positives, 0.45)),
            _round_modifier(_quantile(positives, 0.90)),
        ]
        positive = _strict_thresholds(positive, minimum=0.01)
        positive = [max(positive[0], 0.06), max(positive[1], 0.12)]
        if not positive[0] < positive[1]:
            positive = [0.15, 0.30]
    else:
        positive = [0.15, 0.30]
    # Live modifiers can stack above the generated location-modifier sample.
    # Keep the data-driven lower breaks, then reserve an upper green-to-top band
    # so strong +50% to +75% locations do not collapse into one capped color.
    positive = [*positive, max(positive[-1] + 0.10, 0.75)]

    return {
        "kind": "signed_centered",
        "negative_thresholds": negative,
        "neutral_low": -0.05,
        "neutral_high": 0.05,
        "positive_thresholds": positive,
        "source": "generated_location_modifier_distribution" if numbers else "fallback_static_modifier_scale",
    }


def _reference_scale_dict(values: list[float]) -> dict[str, object]:
    reference = 0.12
    lows = sorted(value for value in values if 0 < value < reference)
    highs = sorted(value for value in values if value > reference)
    if len(lows) >= 5:
        low_thresholds = _strict_thresholds(
            [_round_price(_quantile(lows, 0.20)), _round_price(_quantile(lows, 0.80))],
            minimum=0.001,
        )
    else:
        low_thresholds = [0.02, 0.08]
    if len(highs) >= 5:
        high_thresholds = _strict_thresholds(
            [_round_price(_quantile(highs, 0.45)), _round_price(_quantile(highs, 0.90))],
            minimum=0.001,
        )
    else:
        high_thresholds = [0.18, 0.30]
    low_thresholds = [min(low_thresholds[0], reference - 0.002), min(low_thresholds[1], reference - 0.001)]
    if not low_thresholds[0] < low_thresholds[1] < reference:
        low_thresholds = [0.02, 0.08]
    high_thresholds = [max(high_thresholds[0], reference + 0.001), max(high_thresholds[1], reference + 0.002)]
    if not reference < high_thresholds[0] < high_thresholds[1]:
        high_thresholds = [0.18, 0.30]
    return {
        "kind": "reference_centered",
        "reference": reference,
        "low_thresholds": low_thresholds,
        "high_thresholds": high_thresholds,
        "source": "market_food_price_distribution" if values else "fallback_market_food_price_scale",
    }


def _sequential_scale_dict(thresholds: list[float]) -> dict[str, object]:
    return {"kind": "sequential", "thresholds": thresholds}


def _signed_scale_dict(values: Iterable[float]) -> dict[str, object]:
    return _signed_output_scale_thresholds(values)


def _quantile(values: list[float], q: float) -> float:
    index = max(0, min(len(values) - 1, round((len(values) - 1) * q)))
    return values[index]


def _round_quantity(value: float) -> float:
    if value < 1:
        return round(value, 2)
    if value < 10:
        return round(value * 2) / 2
    if value < 100:
        return round(value)
    return round(value / 10) * 10


def _round_modifier(value: float) -> float:
    return round(value, 2)


def _round_price(value: float) -> float:
    return round(value, 3)


def _strict_thresholds(values: Iterable[float], *, minimum: float) -> list[float]:
    thresholds: list[float] = []
    previous = 0.0
    for raw in values:
        threshold = max(float(raw), previous + minimum)
        thresholds.append(round(threshold, 4))
        previous = thresholds[-1]
    return thresholds


def _strict_thresholds_from_candidates(
    values: Iterable[float],
    candidates: list[float],
    *,
    minimum: float,
) -> list[float]:
    thresholds: list[float] = []
    previous = 0.0
    for raw in values:
        threshold = float(raw)
        if threshold <= previous + minimum:
            replacement = next((candidate for candidate in candidates if candidate > previous + minimum), None)
            threshold = replacement if replacement is not None else previous + minimum
        thresholds.append(round(threshold, 4))
        previous = thresholds[-1]
    return thresholds


if __name__ == "__main__":
    main()
