from __future__ import annotations

import re
import shutil
import tomllib
from pathlib import Path
from typing import Iterable

from eu5gameparser.domain.eu5 import load_eu5_data


ROOT = Path(__file__).resolve().parents[1]
PROJECT_CONFIG = ROOT / "constructor.toml"

MAP_MODE_REL = Path("in_game/gfx/map/map_modes/pp_goods_output_map_modes_generated.txt")
SCRIPT_VALUES_REL = Path("in_game/common/script_values/pp_goods_output_map_modes_generated.txt")
LOCALIZATION_REL = Path("main_menu/localization/english/pp_goods_output_map_modes_l_english.yml")
IN_GAME_ICON_REL = Path("in_game/gfx/interface/icons/map_modes")
TRADE_GOOD_ICON_REL = Path("main_menu/gfx/interface/icons/trade_goods")


def main() -> None:
    project = _load_project_config(PROJECT_CONFIG)
    mod_root = _project_path(project["project"]["mod_root"])
    goods = sorted(_all_goods(project))

    _write_crlf(mod_root / MAP_MODE_REL, _map_modes_file(goods))
    _write_crlf(mod_root / SCRIPT_VALUES_REL, _script_values_file(goods))
    _write_crlf(mod_root / LOCALIZATION_REL, _localization_file(goods))
    _ensure_icons(mod_root, goods, project)
    print(f"Generated goods output map modes for {len(goods)} goods.")


def _load_project_config(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def _project_path(raw: str) -> Path:
    windows_path = _wsl_path_from_windows(raw)
    if windows_path is not None:
        return windows_path
    path = Path(raw)
    return path if path.is_absolute() else (ROOT / path).resolve()


def _wsl_path_from_windows(raw: str) -> Path | None:
    match = re.match(r"^([A-Za-z]):[\\/](.*)$", raw)
    if match is None:
        return None
    drive = match.group(1).lower()
    tail = match.group(2).replace("\\", "/")
    return Path("/mnt") / drive / tail


def _all_goods(project: dict) -> list[str]:
    parser = project.get("parser", {})
    profile = str(parser.get("profile") or "constructor")
    load_order = _project_path(str(parser.get("load_order") or "constructor.load_order.toml"))
    data = load_eu5_data(profile=profile, load_order_path=load_order)
    return data.goods.select("name").to_series().to_list()


def _vanilla_root(project: dict) -> Path:
    parser = project.get("parser", {})
    load_order = _project_path(str(parser.get("load_order") or "constructor.load_order.toml"))
    with load_order.open("rb") as stream:
        raw = tomllib.load(stream)
    paths = raw.get("paths", {})
    vanilla_root = _project_path(str(paths.get("vanilla_root", "")))
    if not vanilla_root.is_absolute():
        vanilla_root = (load_order.parent / vanilla_root).resolve()
    return vanilla_root


def _map_modes_file(goods: Iterable[str]) -> str:
    blocks = [
        "# Generated by tools/generate_pp_goods_output_map_modes.py \u2014 do not edit by hand.",
        "# Heatmap: raw = local output \u00d7 market_access; color factor = clamp(raw / 30, 0, 1) (0\u201330 \u2192 red\u2192green).",
        "# Locations with zero local output of the good get no overlay (terrain); sea/unowned stay grey.",
        "",
        "@pp_goods_output_color_scale_max = 30",
        "",
        "@zoom_step_near = 2",
        "@data_gradient_alpha_inside = 1",
        "@data_gradient_alpha_outside = 1",
        "@data_gradient_width = 0.25",
        "@data_gradient_color_mult = 0.9",
        "@data_edge_width = 0",
        "@data_edge_sharpness = 0.01",
        "@data_edge_alpha = 0",
        "@data_edge_color_mult = 0",
        "@data_before_lighting_blend = 0.5",
        "@data_after_lighting_blend = 0.5",
        "",
    ]
    for good in goods:
        blocks.append(_map_mode_block(good))
    return "\n".join(blocks).rstrip() + "\n"


def _map_mode_block(good: str) -> str:
    upper = good.upper()
    return f"""pp_{good}_output = {{
\tmap_color = {{
\t\tif = {{
\t\t\tlimit = {{
\t\t\t\thas_owner = yes
\t\t\t\t"goods_output(goods:{good})" > 0
\t\t\t}}
\t\t\tlerp = {{
\t\t\t\tmin_color = define:NMapColors|MAP_COLOR_LOW
\t\t\t\tmax_color = define:NMapColors|MAP_COLOR_HIGH
\t\t\t\tfactor = {{
\t\t\t\t\tvalue = pp_{good}_output_raw
\t\t\t\t\tdivide = @pp_goods_output_color_scale_max
\t\t\t\t\tmax = 1
\t\t\t\t\tmin = 0
\t\t\t\t}}
\t\t\t}}
\t\t}}
\t\telse_if = {{
\t\t\tlimit = {{
\t\t\t\tOR = {{
\t\t\t\t\tNOT = {{ has_owner = yes }}
\t\t\t\t\tis_land = no
\t\t\t\t}}
\t\t\t}}
\t\t\tvalue = rgb {{ 128 128 128 }}
\t\t}}
\t}}
\tlegend_key = {{ desc = "MAPMODE_PP_{upper}_OUTPUT" color = define:NMapColors|MAP_COLOR_HIGH }}
\ttooltip_key = {{
\t\tif = {{ limit = {{ is_land = yes }} value = MAPMODE_PP_{upper}_OUTPUT_TT_LAND }}
\t\telse = {{ value = MAPMODE_PP_{upper}_OUTPUT_TT_WATER }}
\t}}
\tsmall_map_names = location
\tmedium_map_names = location
\tlarge_map_names = location
\tsmall_tooltip_context = location
\tmedium_tooltip_context = location
\tlarge_tooltip_context = location
\tfill_in_impassable = yes
\tenable_snow = no
\tflatmap_behaviour = always
\tuse_fow = no
\tcategory = economy
\tindex = 3
\tmap_markers = {{ all = no }}
\tgradient_parameters = {{
\t\tzoom_step = @zoom_step_near
\t\tgradient_alpha_inside = @data_gradient_alpha_inside
\t\tgradient_alpha_outside = @data_gradient_alpha_outside
\t\tgradient_width = @data_gradient_width
\t\tgradient_color_mult = @data_gradient_color_mult
\t\tedge_width = @data_edge_width
\t\tedge_sharpness = @data_edge_sharpness
\t\tedge_alpha = @data_edge_alpha
\t\tedge_color_mult = @data_edge_color_mult
\t\tbefore_lighting_blend = @data_before_lighting_blend
\t\tafter_lighting_blend = @data_after_lighting_blend
\t}}
\tcolor_refresh_counters = {{ Month ProductionList LocationConstructionUnitChanged MarketReach }}
\tcolor_and_names_refresh_counters = {{ LocationOwnerChanged CountryStatus MarketReach }}
}}
"""


def _script_values_file(goods: Iterable[str]) -> str:
    blocks = [
        "# Generated by tools/generate_pp_goods_output_map_modes.py \u2014 do not edit by hand.",
        "# Local monthly goods output \u00d7 location market_access (cf. Location.GetMarketAccess).",
        "",
    ]
    for good in goods:
        blocks.append(_script_value_block(good))
    return "\n".join(blocks).rstrip() + "\n"


def _script_value_block(good: str) -> str:
    return f"""pp_{good}_output_raw = {{
\tvalue = "goods_output(goods:{good})"
\tmultiply = market_access
}}
"""


def _localization_file(goods: Iterable[str]) -> str:
    lines = [
        "l_english:",
        "  # Generated by tools/generate_pp_goods_output_map_modes.py \u2014 do not edit by hand.",
    ]
    for good in goods:
        upper = good.upper()
        lines.extend(
            [
                f'  mapmode_pp_{good}_output_name: "[ShowGoodsName(\'{good}\')|e] Output (\u00d7 Market Access)"',
                f'  MAPMODE_PP_{upper}_OUTPUT: "{_legend_text(good)}"',
                f'  MAPMODE_PP_{upper}_OUTPUT_TT_LAND: "{_land_tooltip_text(good)}"',
                f'  MAPMODE_PP_{upper}_OUTPUT_TT_WATER: "$MAPMODE_PP_LOCAL_OUTPUT_TT_WATER$"',
            ]
        )
    return "\n".join(lines) + "\n"


def _legend_text(good: str) -> str:
    base = (
        f"#T $mapmode_pp_{good}_output_name$#!\\n"
        f"Colors [locations|e] by local [ShowGoodsName('{good}')|e] [output|e] \u00d7 "
        "[market_access|e] from 0 (red) to 30+ (green); values above 30 saturate."
    )
    if good == "marble":
        base += (
            " Marble comes from dedicated [ShowBuildingTypeName('marble_quarry')|e] and "
            "[ShowBuildingTypeName('marble_saw_yard')|e] production."
        )
    return base


def _land_tooltip_text(good: str) -> str:
    base = (
        f"#T $mapmode_pp_{good}_output_name$#!\\n"
        f"[ROOT.GetLocation.GetName]: [ROOT.GetLocation.MakeScope.ScriptValue('pp_{good}_output_raw')|2] = "
        f"[ShowGoodsName('{good}')|e] [output|e] \u00d7 [market_access|e] (per month). Heatmap 0\u201330.\\n"
        "[market_access|e]: [ROOT.GetLocation.GetMarketAccess|2%V]."
    )
    if good == "marble":
        base += (
            "\\n#italic Marble is produced by dedicated [ShowBuildingTypeName('marble_quarry')|e] "
            "and [ShowBuildingTypeName('marble_saw_yard')|e] buildings.#!"
        )
    return base


def _ensure_icons(mod_root: Path, goods: Iterable[str], project: dict) -> None:
    vanilla_root = _vanilla_root(project)
    target = mod_root / IN_GAME_ICON_REL
    target.mkdir(parents=True, exist_ok=True)

    missing: list[str] = []
    for good in goods:
        destination = target / f"pp_{good}_output.dds"
        if destination.exists():
            continue
        source = vanilla_root / "game" / TRADE_GOOD_ICON_REL / f"icon_goods_{good}.dds"
        if source.is_file():
            shutil.copy2(source, destination)
        else:
            missing.append(good)

    if missing:
        raise FileNotFoundError("Missing icon source for goods: " + ", ".join(missing))


def _write_crlf(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="\r\n") as stream:
        stream.write(text)


if __name__ == "__main__":
    main()
